package com.loki.gitresume.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFF5BE48)
val md_theme_dark_onPrimary = Color(0xFF412D00)
val md_theme_dark_primaryContainer = Color(0xFF5D4200)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDEA4)
val md_theme_dark_secondary = Color(0xFFD9C4A0)
val md_theme_dark_onSecondary = Color(0xFF3B2F15)
val md_theme_dark_secondaryContainer = Color(0xFF53452A)
val md_theme_dark_onSecondaryContainer = Color(0xFFF6E0BB)
val md_theme_dark_tertiary = Color(0xFFB2CFA7)
val md_theme_dark_onTertiary = Color(0xFF1F361A)
val md_theme_dark_tertiaryContainer = Color(0xFF354D2F)
val md_theme_dark_onTertiaryContainer = Color(0xFFCEEBC2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1E1B16)
val md_theme_dark_onBackground = Color(0xFFE9E1D9)
val md_theme_dark_surface = Color(0xFF1E1B16)
val md_theme_dark_onSurface = Color(0xFFE9E1D9)
val md_theme_dark_surfaceVariant = Color(0xFF4E4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFD1C5B4)
val md_theme_dark_outline = Color(0xFF9A8F80)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1B16)
val md_theme_dark_inverseSurface = Color(0xFFE9E1D9)
val md_theme_dark_inversePrimary = Color(0xFF7B5800)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFF5BE48)
val md_theme_dark_outlineVariant = Color(0xFF4E4639)
val md_theme_dark_scrim = Color(0xFF000000)